/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Bird.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Bird.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Bone} />
      <primitive object={nodes.Bone011} />
      <skinnedMesh geometry={nodes.Bird_Hand.geometry} material={materials.Bird_Skin} skeleton={nodes.Bird_Hand.skeleton} />
      <skinnedMesh geometry={nodes.Bird_Legs.geometry} material={materials.Bird_Legs} skeleton={nodes.Bird_Legs.skeleton} />
    </group>
  )
}

useGLTF.preload('/Bird.glb')
